### ISSUE TITLE
Yellows8 need payload url

### ISSUE THREAD

**Issue by Mexicanman544** [yellows8/hblauncher_loader#48] opened 2017-02-01 17:04 UTC
when I try to open Homebrew luncher on 3ds its saying that i need the actual payload url with HTTPC

**Comment by Granmazza** [comment] 2017-02-01 17:19
Same issue on 2DS 11.2.0-E35, perhaps the server is down at the moment?

**Comment by yellows8** [comment] 2017-02-01 17:25
Huh? "server is down" no

**Comment by santler** [comment] 2017-02-01 17:28
Hey yellows8, thanks for the reply! I have the same issue, somehow the homebrewlauncher_loader can't access the URL

"Failed to request the actual payload URL: 0xd8a0a028."

I'm also on 2DS 11.2.0-E35

**Comment by Mexicanman544** [comment] 2017-02-01 17:34
I believe it is that im on a old 3ds same update

**Comment by yellows8** [comment] 2017-02-01 17:35
Make sure that your network config doesn't use anything unusual.

**Comment by Mexicanman544** [comment] 2017-02-01 17:40
Do you have any explains of this unusual things.

**Comment by nakku1617** [comment] 2017-02-01 17:43
i have a same problem

**Comment by yellows8** [comment] 2017-02-01 17:45
Also make sure that smea.mtheall.com is accessible from your network.

**Comment by Granmazza** [comment] 2017-02-01 17:46
If so many of us are getting this issue at the sake exact moment than perhaps the problem isn't our network, that would be quite a coincidence

**Comment by Granmazza** [comment] 2017-02-01 17:47
I can access smea.mtheall.com just fine

**Comment by nakku1617** [comment] 2017-02-01 17:47
smea.mtheall.com me too

**Comment by Neostromo** [comment] 2017-02-01 17:47
Fine for me too.

**Comment by Mexicanman544** [comment] 2017-02-01 17:47
Do I type that in the 3ds's internet

**Comment by Neostromo** [comment] 2017-02-01 17:48
Yes. (I guess...)

**Comment by Mexicanman544** [comment] 2017-02-01 17:49
Then what do we after that

**Comment by nakku1617** [comment] 2017-02-01 17:49
i don't know

**Comment by joaodacostaplumbee** [comment] 2017-02-01 17:53
I can access smea.mtheall.com from the 3ds as well

**Comment by santler** [comment] 2017-02-01 17:55
Working fine on the 3DS, just getting a security message beforehand. Don't know if that's important.

**Comment by yellows8** [comment] 2017-02-01 17:56
Just tested it & getting that error with menuhax_manager with stuff accessing \*.mtheall.com.

**Comment by Granmazza** [comment] 2017-02-01 17:58
So the issue isn't on our side?

**Comment by nakku1617** [comment] 2017-02-01 17:58
i don't understand ? server down ?

**Comment by marianocibelli** [comment] 2017-02-01 17:59
Im having the same issue on a N3DS

**Comment by nakku1617** [comment] 2017-02-01 18:01
i have a Old 3ds

**Comment by Granmazza** [comment] 2017-02-01 18:02
So does this mean that while the server appears to work properly our queries for the payload file are getting refused/generating errors?

**Comment by nameghino** [comment] 2017-02-01 18:03
Same with an old 3DS XL here, I can access smea.mtheall.com just fine.

**Comment by nakku1617** [comment] 2017-02-01 18:05
I think it is working on it (sry for my english i'm french )

**Comment by Mexicanman544** [comment] 2017-02-01 18:05
My is error code 012-1511

**Comment by nameghino** [comment] 2017-02-01 18:05
FYI, it is working now

**Comment by yellows8** [comment] 2017-02-01 18:05
Fixed by mtheall.

**Comment by Anonstoner420** [comment] 2017-02-01 18:06
having same problem on N3ds xl. possible server overload?

**Comment by Anonstoner420** [comment] 2017-02-01 18:06
oh nvm

**Comment by nakku1617** [comment] 2017-02-01 18:06
good job man the best !!!

**Comment by nakku1617** [comment] 2017-02-01 18:06
thanks :)

**Comment by Neostromo** [comment] 2017-02-01 18:07
Thanks, you're the best!

**Comment by santler** [comment] 2017-02-01 18:07
Everything fixed, thanks a lot!

**Comment by joaodacostaplumbee** [comment] 2017-02-01 18:10
Confirmed working now on NEW 11.2.0.35-E 
Thanks! :)

**Comment by Mexicanman544** [comment] 2017-02-01 18:13
Got it to work

**Comment by Granmazza** [comment] 2017-02-01 18:13
Thanks dude works like a charm now! Just out of curiosity, how did you fix it?

**Comment by yellows8** [comment] 2017-02-01 18:14
It was the same crypto cipher config issue as last time this error happened.

**Comment by Mexicanman544** [comment] 2017-02-01 18:30
My 3ds gad that stupid parent lock on it and i took it off and it worked for me

**Closed** 2017-02-01 20:19 UTC
